name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        include:
          - php: 8.2
            openspout: ^3.0
            filament: 3.2.142
          - php: 8.3
            openspout: ^4.0
            filament: ^3.3
          - php: 8.4
            openspout: ^4.0
            filament: ^3.3

    name: PHP ${{ matrix.php }} - O${{ matrix.openspout }} - F${{ matrix.filament }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer require "openspout/openspout:${{ matrix.openspout }}" "filament/filament:${{ matrix.filament }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: php artisan test
